#!/bin/bash
# 
# Project: Digibee Realm Switch
# Version: v1.0.0
# Written by: Artur Scheiner
# Email: artur.scheiner@gmail.com

############################################################
# Constants                                                #
############################################################
CONFIG_FILE=~/.digibeectl/config.json
DGB_RS_DIR=~/.dgb-rs

############################################################
# Init                                                     #
############################################################ 
echo "Digibeectl Realm Switch v1.0.0"
mkdir -p $DGB_RS_DIR

############################################################
# Functions                                                #
############################################################
Help()
{
   # Display Help
   echo "Help Information"
   echo 
   echo "Syntax: $0 [-s|a|i|h]"
   echo
   echo "options:"
   echo "s     Switch realm --> $0 -s realm-name"
   echo "a     Add a new realm to the switch list"
   echo "i     Install this script on /usr/local/bin"
   echo "h     Print this Help."
}

Switch()
{
    echo "Set realm based on switch list"
    echo
    LIST=$(ls $DGB_RS_DIR)
    REALM=$1
    if [[ ${LIST[*]} =~ (^|[[:space:]])"$REALM"($|[[:space:]]) ]]; then
       echo "The realm $REALM is available. Switching..."
       echo 
       ln -sf $DGB_RS_DIR/$REALM $CONFIG_FILE
       digibeectl get config
    else
       echo "Could not switch to the realm $REALM."
       echo "Check-out the available realms to switch to:"
       echo
       ListRealms
    fi
}

Deploy()
{
    chmod +x $0
    sudo cp $0 /usr/local/bin
}

Add()
{
    echo "Add a new realm to the switch list"
    echo
    
    if [ -f "$CONFIG_FILE" ] && [ ! -h "$CONFIG_FILE" ]; then
       REALM=$(digibeectl get config | grep realm | awk '{print $2}')

       echo "Digibeectl is configured to:"
       digibeectl get config
       echo 
       echo "Adding realm $REALM to the available list"
       cp $CONFIG_FILE $DGB_RS_DIR/$REALM

       Switch $REALM
    else
       echo "Digibeectl is not configured"
       echo 'digibeectl set config \
            --file "path/file.json" \
            --secret-key "encryption-key" \
            --auth-key "encryption-passphrase"'
       echo
    fi
}

List()
{
    echo "List configured realms"
    echo
    echo "The realms listed bellow are already configured:"
    echo 
    ListRealms
    echo
}

ListRealms()
{
    for c in $(ls $DGB_RS_DIR); do echo "  - $c"; done
}

############################################################
# Main program                                             #
############################################################

############################################################
# Process the input options.                               #
############################################################
# Get the options

while getopts "hils:a:" option; do
   case $option in
      a) # config
         Add
         exit;;
      h) # display Help
         Help
         exit;;
      s) # switch realm
         Switch $OPTARG
         exit;;
      d) # deploy script
         Deploy
         exit;;
      l) # list script
         List
         exit;;
     \?) # Invalid option
         echo 
         echo "Error: Invalid option"
         echo
         exit;;
   esac
done

echo "$@"
echo "Hello $Name!"

